project:
  type: website
  output-dir: docs

website:
  title: "BST 260: Introduction to Data Science"
  site-url: "https://datasciencelabs.github.io/2025/"
  repo-url: "https://github.com/datasciencelabs/2025"
  repo-branch: main
  repo-actions: [source]
  sidebar:
    background: primary
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: "https://github.com/datasciencelabs/2025"
        text: GitHub
    style: docked
    contents:
    - href: index.qmd
      text: Home
    - href: slides.qmd
      text: Slides
    - href: psets.qmd
      text: Problem Sets
    - href: syllabus.qmd
      text: Syllabus
    - href: final-project.qmd
      text: Final Project
    
format:
  html:
    theme: journal
    css: style.css
    toc: true

editor: source