project:
  type: website
  output-dir: docs
  # This section explicitly tells Quarto to copy these files to the output directory
  resources: 
    - "style.css"
    - "images/" # Also good practice to list other resource folders

website:
  title: "BST 260: Introduction to Data Science"
  site-url: "https://datasciencelabs.github.io/2025/" # Use https and trailing slash
  repo-url: "https://github.com/datasciencelabs/2025"
  repo-branch: main
  repo-actions: [source]
  sidebar:
    background: primary
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: "https://github.com/datasciencelabs/2025"
        text: GitHub
    style: docked
    contents:
    - href: index.qmd
      text: Home
    - href: slides.qmd
      text: Slides
    - href: psets.qmd
      text: Problem Sets
    - href: syllabus.qmd
      text: Syllabus
    - href: final-project.qmd
      text: Final Project
    
format:
  html:
    css: style.scss 
    toc: true

editor: source