<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-11-04">
<meta name="keywords" content="Linear Models">

<title>Regression – BST 260: Introduction to Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8e0d6fe173fc884be9977477430247b6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../style.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Regression</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/datasciencelabs/2025" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Slides</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../psets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Sets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../oral-evaluations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Oral Evaluations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../final-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#case-study-is-height-hereditary" id="toc-case-study-is-height-hereditary" class="nav-link active" data-scroll-target="#case-study-is-height-hereditary">Case study: is height hereditary?</a></li>
  <li><a href="#case-study-is-height-hereditary-1" id="toc-case-study-is-height-hereditary-1" class="nav-link" data-scroll-target="#case-study-is-height-hereditary-1">Case study: is height hereditary?</a></li>
  <li><a href="#case-study-is-height-hereditary-2" id="toc-case-study-is-height-hereditary-2" class="nav-link" data-scroll-target="#case-study-is-height-hereditary-2">Case study: is height hereditary?</a></li>
  <li><a href="#case-study-is-height-hereditary-3" id="toc-case-study-is-height-hereditary-3" class="nav-link" data-scroll-target="#case-study-is-height-hereditary-3">Case study: is height hereditary?</a></li>
  <li><a href="#case-study-is-height-hereditary-4" id="toc-case-study-is-height-hereditary-4" class="nav-link" data-scroll-target="#case-study-is-height-hereditary-4">Case study: is height hereditary?</a></li>
  <li><a href="#case-study-is-height-hereditary-5" id="toc-case-study-is-height-hereditary-5" class="nav-link" data-scroll-target="#case-study-is-height-hereditary-5">Case study: is height hereditary?</a></li>
  <li><a href="#case-study-is-height-hereditary-6" id="toc-case-study-is-height-hereditary-6" class="nav-link" data-scroll-target="#case-study-is-height-hereditary-6">Case study: is height hereditary?</a></li>
  <li><a href="#the-correlation-coefficient" id="toc-the-correlation-coefficient" class="nav-link" data-scroll-target="#the-correlation-coefficient">The correlation coefficient</a></li>
  <li><a href="#the-correlation-coefficient-1" id="toc-the-correlation-coefficient-1" class="nav-link" data-scroll-target="#the-correlation-coefficient-1">The correlation coefficient</a></li>
  <li><a href="#the-correlation-coefficient-2" id="toc-the-correlation-coefficient-2" class="nav-link" data-scroll-target="#the-correlation-coefficient-2">The correlation coefficient</a></li>
  <li><a href="#the-correlation-coefficient-3" id="toc-the-correlation-coefficient-3" class="nav-link" data-scroll-target="#the-correlation-coefficient-3">The correlation coefficient</a></li>
  <li><a href="#the-correlation-coefficient-4" id="toc-the-correlation-coefficient-4" class="nav-link" data-scroll-target="#the-correlation-coefficient-4">The correlation coefficient</a></li>
  <li><a href="#the-correlation-coefficient-5" id="toc-the-correlation-coefficient-5" class="nav-link" data-scroll-target="#the-correlation-coefficient-5">The correlation coefficient</a></li>
  <li><a href="#the-correlation-coefficient-6" id="toc-the-correlation-coefficient-6" class="nav-link" data-scroll-target="#the-correlation-coefficient-6">The correlation coefficient</a></li>
  <li><a href="#sample-correlation-is-random" id="toc-sample-correlation-is-random" class="nav-link" data-scroll-target="#sample-correlation-is-random">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-1" id="toc-sample-correlation-is-random-1" class="nav-link" data-scroll-target="#sample-correlation-is-random-1">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-2" id="toc-sample-correlation-is-random-2" class="nav-link" data-scroll-target="#sample-correlation-is-random-2">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-3" id="toc-sample-correlation-is-random-3" class="nav-link" data-scroll-target="#sample-correlation-is-random-3">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-4" id="toc-sample-correlation-is-random-4" class="nav-link" data-scroll-target="#sample-correlation-is-random-4">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-5" id="toc-sample-correlation-is-random-5" class="nav-link" data-scroll-target="#sample-correlation-is-random-5">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-6" id="toc-sample-correlation-is-random-6" class="nav-link" data-scroll-target="#sample-correlation-is-random-6">Sample correlation is random</a></li>
  <li><a href="#sample-correlation-is-random-7" id="toc-sample-correlation-is-random-7" class="nav-link" data-scroll-target="#sample-correlation-is-random-7">Sample correlation is random</a></li>
  <li><a href="#correlation-not-always-useful" id="toc-correlation-not-always-useful" class="nav-link" data-scroll-target="#correlation-not-always-useful">Correlation not always useful</a></li>
  <li><a href="#correlation-not-always-useful-1" id="toc-correlation-not-always-useful-1" class="nav-link" data-scroll-target="#correlation-not-always-useful-1">Correlation not always useful</a></li>
  <li><a href="#correlation-not-always-useful-2" id="toc-correlation-not-always-useful-2" class="nav-link" data-scroll-target="#correlation-not-always-useful-2">Correlation not always useful</a></li>
  <li><a href="#conditional-expectations" id="toc-conditional-expectations" class="nav-link" data-scroll-target="#conditional-expectations">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-1" id="toc-conditional-expectations-1" class="nav-link" data-scroll-target="#conditional-expectations-1">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-2" id="toc-conditional-expectations-2" class="nav-link" data-scroll-target="#conditional-expectations-2">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-3" id="toc-conditional-expectations-3" class="nav-link" data-scroll-target="#conditional-expectations-3">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-4" id="toc-conditional-expectations-4" class="nav-link" data-scroll-target="#conditional-expectations-4">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-5" id="toc-conditional-expectations-5" class="nav-link" data-scroll-target="#conditional-expectations-5">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-6" id="toc-conditional-expectations-6" class="nav-link" data-scroll-target="#conditional-expectations-6">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-7" id="toc-conditional-expectations-7" class="nav-link" data-scroll-target="#conditional-expectations-7">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-8" id="toc-conditional-expectations-8" class="nav-link" data-scroll-target="#conditional-expectations-8">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-9" id="toc-conditional-expectations-9" class="nav-link" data-scroll-target="#conditional-expectations-9">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-10" id="toc-conditional-expectations-10" class="nav-link" data-scroll-target="#conditional-expectations-10">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-11" id="toc-conditional-expectations-11" class="nav-link" data-scroll-target="#conditional-expectations-11">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-12" id="toc-conditional-expectations-12" class="nav-link" data-scroll-target="#conditional-expectations-12">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-13" id="toc-conditional-expectations-13" class="nav-link" data-scroll-target="#conditional-expectations-13">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-14" id="toc-conditional-expectations-14" class="nav-link" data-scroll-target="#conditional-expectations-14">Conditional expectations</a></li>
  <li><a href="#conditional-expectations-15" id="toc-conditional-expectations-15" class="nav-link" data-scroll-target="#conditional-expectations-15">Conditional expectations</a></li>
  <li><a href="#the-regression-line" id="toc-the-regression-line" class="nav-link" data-scroll-target="#the-regression-line">The regression line</a></li>
  <li><a href="#the-regression-line-1" id="toc-the-regression-line-1" class="nav-link" data-scroll-target="#the-regression-line-1">The regression line</a></li>
  <li><a href="#the-regression-line-2" id="toc-the-regression-line-2" class="nav-link" data-scroll-target="#the-regression-line-2">The regression line</a></li>
  <li><a href="#the-regression-line-3" id="toc-the-regression-line-3" class="nav-link" data-scroll-target="#the-regression-line-3">The regression line</a></li>
  <li><a href="#the-regression-line-4" id="toc-the-regression-line-4" class="nav-link" data-scroll-target="#the-regression-line-4">The regression line</a></li>
  <li><a href="#the-regression-line-5" id="toc-the-regression-line-5" class="nav-link" data-scroll-target="#the-regression-line-5">The regression line</a></li>
  <li><a href="#the-regression-line-6" id="toc-the-regression-line-6" class="nav-link" data-scroll-target="#the-regression-line-6">The regression line</a></li>
  <li><a href="#the-regression-line-7" id="toc-the-regression-line-7" class="nav-link" data-scroll-target="#the-regression-line-7">The regression line</a></li>
  <li><a href="#the-regression-line-8" id="toc-the-regression-line-8" class="nav-link" data-scroll-target="#the-regression-line-8">The regression line</a></li>
  <li><a href="#regression-improves-precision" id="toc-regression-improves-precision" class="nav-link" data-scroll-target="#regression-improves-precision">Regression improves precision</a></li>
  <li><a href="#regression-improves-precision-1" id="toc-regression-improves-precision-1" class="nav-link" data-scroll-target="#regression-improves-precision-1">Regression improves precision</a></li>
  <li><a href="#regression-improves-precision-2" id="toc-regression-improves-precision-2" class="nav-link" data-scroll-target="#regression-improves-precision-2">Regression improves precision</a></li>
  <li><a href="#regression-improves-precision-3" id="toc-regression-improves-precision-3" class="nav-link" data-scroll-target="#regression-improves-precision-3">Regression improves precision</a></li>
  <li><a href="#regression-improves-precision-4" id="toc-regression-improves-precision-4" class="nav-link" data-scroll-target="#regression-improves-precision-4">Regression improves precision</a></li>
  <li><a href="#regression-improves-precision-5" id="toc-regression-improves-precision-5" class="nav-link" data-scroll-target="#regression-improves-precision-5">Regression improves precision</a></li>
  <li><a href="#bivariate-normal-distribution" id="toc-bivariate-normal-distribution" class="nav-link" data-scroll-target="#bivariate-normal-distribution">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-1" id="toc-bivariate-normal-distribution-1" class="nav-link" data-scroll-target="#bivariate-normal-distribution-1">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-2" id="toc-bivariate-normal-distribution-2" class="nav-link" data-scroll-target="#bivariate-normal-distribution-2">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-3" id="toc-bivariate-normal-distribution-3" class="nav-link" data-scroll-target="#bivariate-normal-distribution-3">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-4" id="toc-bivariate-normal-distribution-4" class="nav-link" data-scroll-target="#bivariate-normal-distribution-4">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-5" id="toc-bivariate-normal-distribution-5" class="nav-link" data-scroll-target="#bivariate-normal-distribution-5">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-6" id="toc-bivariate-normal-distribution-6" class="nav-link" data-scroll-target="#bivariate-normal-distribution-6">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-7" id="toc-bivariate-normal-distribution-7" class="nav-link" data-scroll-target="#bivariate-normal-distribution-7">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-8" id="toc-bivariate-normal-distribution-8" class="nav-link" data-scroll-target="#bivariate-normal-distribution-8">Bivariate normal distribution</a></li>
  <li><a href="#bivariate-normal-distribution-9" id="toc-bivariate-normal-distribution-9" class="nav-link" data-scroll-target="#bivariate-normal-distribution-9">Bivariate normal distribution</a></li>
  <li><a href="#variance-explained" id="toc-variance-explained" class="nav-link" data-scroll-target="#variance-explained">Variance explained</a></li>
  <li><a href="#variance-explained-1" id="toc-variance-explained-1" class="nav-link" data-scroll-target="#variance-explained-1">Variance explained</a></li>
  <li><a href="#variance-explained-2" id="toc-variance-explained-2" class="nav-link" data-scroll-target="#variance-explained-2">Variance explained</a></li>
  <li><a href="#variance-explained-3" id="toc-variance-explained-3" class="nav-link" data-scroll-target="#variance-explained-3">Variance explained</a></li>
  <li><a href="#there-are-two-regression-lines" id="toc-there-are-two-regression-lines" class="nav-link" data-scroll-target="#there-are-two-regression-lines">There are two regression lines</a></li>
  <li><a href="#there-are-two-regression-lines-1" id="toc-there-are-two-regression-lines-1" class="nav-link" data-scroll-target="#there-are-two-regression-lines-1">There are two regression lines</a></li>
  <li><a href="#there-are-two-regression-lines-2" id="toc-there-are-two-regression-lines-2" class="nav-link" data-scroll-target="#there-are-two-regression-lines-2">There are two regression lines</a></li>
  <li><a href="#there-are-two-regression-lines-3" id="toc-there-are-two-regression-lines-3" class="nav-link" data-scroll-target="#there-are-two-regression-lines-3">There are two regression lines</a></li>
  <li><a href="#linear-models" id="toc-linear-models" class="nav-link" data-scroll-target="#linear-models">Linear models</a></li>
  <li><a href="#linear-models-1" id="toc-linear-models-1" class="nav-link" data-scroll-target="#linear-models-1">Linear models</a></li>
  <li><a href="#linear-models-2" id="toc-linear-models-2" class="nav-link" data-scroll-target="#linear-models-2">Linear models</a></li>
  <li><a href="#linear-models-3" id="toc-linear-models-3" class="nav-link" data-scroll-target="#linear-models-3">Linear models</a></li>
  <li><a href="#linear-models-4" id="toc-linear-models-4" class="nav-link" data-scroll-target="#linear-models-4">Linear models</a></li>
  <li><a href="#linear-models-5" id="toc-linear-models-5" class="nav-link" data-scroll-target="#linear-models-5">Linear models</a></li>
  <li><a href="#linear-models-6" id="toc-linear-models-6" class="nav-link" data-scroll-target="#linear-models-6">Linear models</a></li>
  <li><a href="#linear-models-7" id="toc-linear-models-7" class="nav-link" data-scroll-target="#linear-models-7">Linear models</a></li>
  <li><a href="#linear-models-8" id="toc-linear-models-8" class="nav-link" data-scroll-target="#linear-models-8">Linear models</a></li>
  <li><a href="#linear-models-9" id="toc-linear-models-9" class="nav-link" data-scroll-target="#linear-models-9">Linear models</a></li>
  <li><a href="#linear-models-10" id="toc-linear-models-10" class="nav-link" data-scroll-target="#linear-models-10">Linear models</a></li>
  <li><a href="#linear-models-11" id="toc-linear-models-11" class="nav-link" data-scroll-target="#linear-models-11">Linear models</a></li>
  <li><a href="#linear-models-12" id="toc-linear-models-12" class="nav-link" data-scroll-target="#linear-models-12">Linear models</a></li>
  <li><a href="#least-squares-estimates" id="toc-least-squares-estimates" class="nav-link" data-scroll-target="#least-squares-estimates">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-1" id="toc-least-squares-estimates-1" class="nav-link" data-scroll-target="#least-squares-estimates-1">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-2" id="toc-least-squares-estimates-2" class="nav-link" data-scroll-target="#least-squares-estimates-2">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-3" id="toc-least-squares-estimates-3" class="nav-link" data-scroll-target="#least-squares-estimates-3">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-4" id="toc-least-squares-estimates-4" class="nav-link" data-scroll-target="#least-squares-estimates-4">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-5" id="toc-least-squares-estimates-5" class="nav-link" data-scroll-target="#least-squares-estimates-5">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-6" id="toc-least-squares-estimates-6" class="nav-link" data-scroll-target="#least-squares-estimates-6">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-7" id="toc-least-squares-estimates-7" class="nav-link" data-scroll-target="#least-squares-estimates-7">Least Squares Estimates</a></li>
  <li><a href="#least-squares-estimates-8" id="toc-least-squares-estimates-8" class="nav-link" data-scroll-target="#least-squares-estimates-8">Least Squares Estimates</a></li>
  <li><a href="#the-lm-function" id="toc-the-lm-function" class="nav-link" data-scroll-target="#the-lm-function">The <code>lm</code> function</a></li>
  <li><a href="#the-lm-function-1" id="toc-the-lm-function-1" class="nav-link" data-scroll-target="#the-lm-function-1">The <code>lm</code> function</a></li>
  <li><a href="#the-lm-function-2" id="toc-the-lm-function-2" class="nav-link" data-scroll-target="#the-lm-function-2">The <code>lm</code> function</a></li>
  <li><a href="#the-lm-function-3" id="toc-the-lm-function-3" class="nav-link" data-scroll-target="#the-lm-function-3">The <code>lm</code> function</a></li>
  <li><a href="#lse-are-random-variables" id="toc-lse-are-random-variables" class="nav-link" data-scroll-target="#lse-are-random-variables">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-1" id="toc-lse-are-random-variables-1" class="nav-link" data-scroll-target="#lse-are-random-variables-1">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-2" id="toc-lse-are-random-variables-2" class="nav-link" data-scroll-target="#lse-are-random-variables-2">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-3" id="toc-lse-are-random-variables-3" class="nav-link" data-scroll-target="#lse-are-random-variables-3">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-4" id="toc-lse-are-random-variables-4" class="nav-link" data-scroll-target="#lse-are-random-variables-4">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-5" id="toc-lse-are-random-variables-5" class="nav-link" data-scroll-target="#lse-are-random-variables-5">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-6" id="toc-lse-are-random-variables-6" class="nav-link" data-scroll-target="#lse-are-random-variables-6">LSE are random variables</a></li>
  <li><a href="#lse-are-random-variables-7" id="toc-lse-are-random-variables-7" class="nav-link" data-scroll-target="#lse-are-random-variables-7">LSE are random variables</a></li>
  <li><a href="#predicted-values-are-random-variables" id="toc-predicted-values-are-random-variables" class="nav-link" data-scroll-target="#predicted-values-are-random-variables">Predicted values are random variables</a></li>
  <li><a href="#predicted-values-are-random-variables-1" id="toc-predicted-values-are-random-variables-1" class="nav-link" data-scroll-target="#predicted-values-are-random-variables-1">Predicted values are random variables</a></li>
  <li><a href="#predicted-values-are-random-variables-2" id="toc-predicted-values-are-random-variables-2" class="nav-link" data-scroll-target="#predicted-values-are-random-variables-2">Predicted values are random variables</a></li>
  <li><a href="#predicted-values-are-random-variables-3" id="toc-predicted-values-are-random-variables-3" class="nav-link" data-scroll-target="#predicted-values-are-random-variables-3">Predicted values are random variables</a></li>
  <li><a href="#predicted-values-are-random-variables-4" id="toc-predicted-values-are-random-variables-4" class="nav-link" data-scroll-target="#predicted-values-are-random-variables-4">Predicted values are random variables</a></li>
  <li><a href="#diagnostic-plots" id="toc-diagnostic-plots" class="nav-link" data-scroll-target="#diagnostic-plots">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-1" id="toc-diagnostic-plots-1" class="nav-link" data-scroll-target="#diagnostic-plots-1">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-2" id="toc-diagnostic-plots-2" class="nav-link" data-scroll-target="#diagnostic-plots-2">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-3" id="toc-diagnostic-plots-3" class="nav-link" data-scroll-target="#diagnostic-plots-3">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-4" id="toc-diagnostic-plots-4" class="nav-link" data-scroll-target="#diagnostic-plots-4">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-5" id="toc-diagnostic-plots-5" class="nav-link" data-scroll-target="#diagnostic-plots-5">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-6" id="toc-diagnostic-plots-6" class="nav-link" data-scroll-target="#diagnostic-plots-6">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-7" id="toc-diagnostic-plots-7" class="nav-link" data-scroll-target="#diagnostic-plots-7">Diagnostic plots</a></li>
  <li><a href="#diagnostic-plots-8" id="toc-diagnostic-plots-8" class="nav-link" data-scroll-target="#diagnostic-plots-8">Diagnostic plots</a></li>
  <li><a href="#the-regression-fallacy" id="toc-the-regression-fallacy" class="nav-link" data-scroll-target="#the-regression-fallacy">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-1" id="toc-the-regression-fallacy-1" class="nav-link" data-scroll-target="#the-regression-fallacy-1">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-2" id="toc-the-regression-fallacy-2" class="nav-link" data-scroll-target="#the-regression-fallacy-2">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-3" id="toc-the-regression-fallacy-3" class="nav-link" data-scroll-target="#the-regression-fallacy-3">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-4" id="toc-the-regression-fallacy-4" class="nav-link" data-scroll-target="#the-regression-fallacy-4">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-5" id="toc-the-regression-fallacy-5" class="nav-link" data-scroll-target="#the-regression-fallacy-5">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-6" id="toc-the-regression-fallacy-6" class="nav-link" data-scroll-target="#the-regression-fallacy-6">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-7" id="toc-the-regression-fallacy-7" class="nav-link" data-scroll-target="#the-regression-fallacy-7">The regression fallacy</a></li>
  <li><a href="#the-regression-fallacy-8" id="toc-the-regression-fallacy-8" class="nav-link" data-scroll-target="#the-regression-fallacy-8">The regression fallacy</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/datasciencelabs/2025/blob/main/slides/linear-models/29-regression.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="29-regression.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 4, 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>Linear Models</p>
  </div>
</div>

</header>


<section id="case-study-is-height-hereditary" class="level2">
<h2 class="anchored" data-anchor-id="case-study-is-height-hereditary">Case study: is height hereditary?</h2>
<ul>
<li><p>To understand the concepts of correlation and simple regression, we actually use the dataset from which regression was born.</p></li>
<li><p>The example is from genetics.</p></li>
<li><p>Francis Galton studied the variation and heredity of human traits.</p></li>
<li><p>Among many other traits, Galton collected and studied height data from families to try to understand heredity.</p></li>
</ul>
</section>
<section id="case-study-is-height-hereditary-1" class="level2">
<h2 class="anchored" data-anchor-id="case-study-is-height-hereditary-1">Case study: is height hereditary?</h2>
<ul>
<li><p>While doing this, he developed the concepts of correlation and regression.</p></li>
<li><p>At the time this data was collected, our knowledge of genetics was limited compared to what we know today.</p></li>
<li><p>A very specific question Galton tried to answer was: <strong>how well can we predict a child’s height based on the parents’ height?</strong></p></li>
</ul>
</section>
<section id="case-study-is-height-hereditary-2" class="level2">
<h2 class="anchored" data-anchor-id="case-study-is-height-hereditary-2">Case study: is height hereditary?</h2>
<ul>
<li><p>We have access to Galton’s family height data through the <strong>HistData</strong> package.</p></li>
<li><p>This data contains heights on several dozen families: mothers, fathers, daughters, and sons.</p></li>
</ul>
</section>
<section id="case-study-is-height-hereditary-3" class="level2">
<h2 class="anchored" data-anchor-id="case-study-is-height-hereditary-3">Case study: is height hereditary?</h2>
<ul>
<li>To imitate Galton’s analysis, we will create a dataset with the heights of fathers and a randomly selected son of each family:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(HistData) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1983</span>) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="ot">&lt;-</span> GaltonFamilies <span class="sc">|&gt;</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="st">"male"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(family) <span class="sc">|&gt;</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(father, childHeight) <span class="sc">|&gt;</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">son =</span> childHeight) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="case-study-is-height-hereditary-4" class="level2">
<h2 class="anchored" data-anchor-id="case-study-is-height-hereditary-4">Case study: is height hereditary?</h2>
<ul>
<li><p>Suppose we were asked to summarize the father and son data.</p></li>
<li><p>Since both distributions are well approximated by the normal distribution, we could use:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="sc">|&gt;</span>  </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(father), <span class="fu">sd</span>(father), <span class="fu">mean</span>(son), <span class="fu">sd</span>(son)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  `mean(father)` `sd(father)` `mean(son)` `sd(son)`
           &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
1           69.1         2.55        69.2      2.71</code></pre>
</div>
</div>
</section>
<section id="case-study-is-height-hereditary-5" class="level2">
<h2 class="anchored" data-anchor-id="case-study-is-height-hereditary-5">Case study: is height hereditary?</h2>
<ul>
<li>This summary fails to describe an important characteristic of the data:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/scatterplot-run-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="case-study-is-height-hereditary-6" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="case-study-is-height-hereditary-6">Case study: is height hereditary?</h2>
<ul>
<li><p>The Pearson correlation coefficient is an informative summary of how two variables move together.</p></li>
<li><p>we can define the sample correlation for any bivariate set of data</p></li>
<li><p>It’s defined for a list of pairs <span class="math inline">\((x_1, y_1), \dots, (x_n,y_n)\)</span> as:</p></li>
</ul>
<p><span class="math display">\[
\rho = \frac{1}{n} \sum_{i=1}^n \left( \frac{x_i-\bar{x}}{s_x} \right)\left( \frac{y_i-\bar{y}}{s_y} \right)
\]</span> - with <span class="math inline">\(\bar{x}, \bar{y}\)</span> the sample means of <span class="math inline">\(x_1,\dots, x_n\)</span> and <span class="math inline">\(y_1, \dots, y_n\)</span>, respectively, and <span class="math inline">\(s_x, s_y\)</span> the sample standard deviations.</p>
</section>
<section id="the-correlation-coefficient" class="level2">
<h2 class="anchored" data-anchor-id="the-correlation-coefficient">The correlation coefficient</h2>
<ul>
<li><p><span class="math inline">\(\rho\)</span> is the greek letter for <span class="math inline">\(r\)</span>.</p></li>
<li><p>It is not a coincidence that <span class="math inline">\(r\)</span> is the first letter in <em>regression</em>.</p></li>
<li><p>We will learn about the connection between correlation and regression.</p></li>
</ul>
</section>
<section id="the-correlation-coefficient-1" class="level2">
<h2 class="anchored" data-anchor-id="the-correlation-coefficient-1">The correlation coefficient</h2>
<ul>
<li>We can represent the formula above with R code using:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">scale</span>(x) <span class="sc">*</span> <span class="fu">scale</span>(y)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-correlation-coefficient-2" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-correlation-coefficient-2">The correlation coefficient</h2>
<ul>
<li><p>To understand why this equation does in fact summarize how two variables move together, note that the <span class="math inline">\(i\)</span>-th entry of <span class="math inline">\(x\)</span> is <span class="math inline">\(\left( \frac{x_i-\bar{x}}{s_x} \right)\)</span> SDs away from the average.</p></li>
<li><p>Similarly, the <span class="math inline">\(y_i\)</span> that is paired with <span class="math inline">\(x_i\)</span>, is <span class="math inline">\(\left( \frac{y_1-\bar{y}}{s_y} \right)\)</span> SDs away from the average <span class="math inline">\(y\)</span>.</p></li>
<li><p>If <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are unrelated, the product <span class="math display">\[
\left( \frac{x_i-\bar{x}}{s_x} \right) \cdot \left( \frac{y_i-\bar{y}}{s_y} \right)
\]</span> will be positive ( <span class="math inline">\(+ \times +\)</span> and <span class="math inline">\(- \times -\)</span> ) as often as negative (<span class="math inline">\(+ \times -\)</span> and <span class="math inline">\(- \times +\)</span>) and will average out to about 0.</p></li>
<li><p>this correlation measure linear relationships and is less informative if <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> have a non-linear relationship</p></li>
</ul>
</section>
<section id="the-correlation-coefficient-3" class="level2">
<h2 class="anchored" data-anchor-id="the-correlation-coefficient-3">The correlation coefficient</h2>
<ul>
<li><p>The Pearson correlation is the average of the product of those deviations and therefore unrelated variables will have a correlation close to zero</p></li>
<li><p>If instead the quantities vary together, say higher values of x go with higher values of y, then we are averaging mostly positive products so we get a positive correlation</p></li>
<li><p>If large values of x go with smaller values of y, then we are averaging mostly negative values, and we get a negative correlation</p></li>
</ul>
</section>
<section id="the-correlation-coefficient-4" class="level2">
<h2 class="anchored" data-anchor-id="the-correlation-coefficient-4">The correlation coefficient</h2>
<ul>
<li><p>The correlation coefficient is always between -1 and 1.</p></li>
<li><p>the sample correlation coefficient is 1 or -1 only when x and y lie exactly on a straight line.</p></li>
<li><p>We can show these facts mathematically.</p></li>
</ul>
</section>
<section id="the-correlation-coefficient-5" class="level2">
<h2 class="anchored" data-anchor-id="the-correlation-coefficient-5">The correlation coefficient</h2>
<ul>
<li>The correlation, computed with the function <code>cor</code>, between father and son’s heights is about 0.5:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(father, son)) <span class="sc">|&gt;</span> <span class="fu">pull</span>(r) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4334102</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>The function <code>cor(x, y)</code> computes the sample correlation, which divides the sum of products by <code>length(x)-1</code> rather than <code>length(x)</code>.</p></li>
<li><p>The rationale for this is akin to the reason we divide by <code>length(x)-1</code> when computing the sample standard deviation <code>sd(x)</code>.</p></li>
<li><p>Namely, this adjustment helps account for the degrees of freedom in the sample, which is necessary for unbiased estimates.</p></li>
</ul>
</div>
</div>
</section>
<section id="the-correlation-coefficient-6" class="level2">
<h2 class="anchored" data-anchor-id="the-correlation-coefficient-6">The correlation coefficient</h2>
<ul>
<li>Correlations ranging from -0.9 to 0.99:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/what-correlation-looks-like-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sample-correlation-is-random" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random">Sample correlation is random</h2>
<ul>
<li><p>Before we continue connecting correlation to regression, let’s remind ourselves about random variability.</p></li>
<li><p>In most applications, we observe data that includes random variation.</p></li>
<li><p>For example, in many cases, we do not observe data for the entire population of interest, but rather for a random sample.</p></li>
<li><p>As with the average and standard deviation, the <em>sample correlation</em> is the most commonly used estimate of the population correlation.</p></li>
</ul>
</section>
<section id="sample-correlation-is-random-1" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-1">Sample correlation is random</h2>
<ul>
<li><p>This implies that the correlation we compute and use as a summary is a random variable.</p></li>
<li><p>By way of illustration, let’s assume that the 179 pairs of fathers and sons is our entire population.</p></li>
</ul>
</section>
<section id="sample-correlation-is-random-2" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-2">Sample correlation is random</h2>
<ul>
<li><p>A less fortunate geneticist can only afford measurements from a random sample of 25 pairs.</p></li>
<li><p>The sample correlation can be computed with:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(galton_heights, <span class="dv">25</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(father, son)) <span class="sc">|&gt;</span> <span class="fu">pull</span>(r) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>r</code> is a random variable.</li>
</ul>
</section>
<section id="sample-correlation-is-random-3" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-3">Sample correlation is random</h2>
<ul>
<li>We can run a Monte Carlo simulation to see its distribution:</li>
</ul>
<div class="cell" data-layout-align="center" data-output-location="slide">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">25</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, { </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(galton_heights, N, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">r =</span> <span class="fu">cor</span>(father, son)) <span class="sc">|&gt;</span>  </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(r) </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>}) </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(r, <span class="at">breaks =</span> <span class="dv">20</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/sample-correlation-distribution-run-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sample-correlation-is-random-4" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-4">Sample correlation is random</h2>
<ul>
<li>We see that the expected value of <code>r</code> is the population correlation:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(r) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4307393</code></pre>
</div>
</div>
<ul>
<li>and that it has a relatively high standard error relative to the range of values <code>r</code> can take:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(r) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1609393</code></pre>
</div>
</div>
</section>
<section id="sample-correlation-is-random-5" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-5">Sample correlation is random</h2>
<ul>
<li><p>So, when interpreting correlations, remember that correlations derived from samples are estimates containing uncertainty.</p></li>
<li><p>Also, note that because the sample correlation is an average of independent draws, the central limit actually applies.</p></li>
<li><p>Therefore, for large enough <span class="math inline">\(N\)</span>, the distribution of <code>r</code> is approximately normal with expected value <span class="math inline">\(\rho\)</span>.</p></li>
</ul>
</section>
<section id="sample-correlation-is-random-6" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-6">Sample correlation is random</h2>
<ul>
<li>The standard deviation, which is somewhat complex to derive, is <span class="math inline">\(\sqrt{\frac{1-r^2}{N-2}}\)</span>.</li>
</ul>
</section>
<section id="sample-correlation-is-random-7" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-is-random-7">Sample correlation is random</h2>
<ul>
<li><span class="math inline">\(N=25\)</span> does not seem to be large enough to get a good approximation to the Normal distribution:</li>
</ul>
<div class="cell" data-layout-align="center" data-output-location="slide">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> r), <span class="at">data =</span> <span class="fu">data.frame</span>(r)) <span class="sc">+</span>  </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span>  </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">mean</span>(r), <span class="at">slope =</span> <span class="fu">sqrt</span>((<span class="dv">1</span> <span class="sc">-</span> <span class="fu">mean</span>(r)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(N <span class="sc">-</span> <span class="dv">2</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/small-sample-correlation-not-normal-run-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="correlation-not-always-useful" class="level2">
<h2 class="anchored" data-anchor-id="correlation-not-always-useful">Correlation not always useful</h2>
<ul>
<li><p>Correlation is not always a good summary of the relationship between two variables.</p></li>
<li><p>The following four artificial datasets, referred to as Anscombe’s quartet, famously illustrate this point.</p></li>
</ul>
</section>
<section id="correlation-not-always-useful-1" class="level2">
<h2 class="anchored" data-anchor-id="correlation-not-always-useful-1">Correlation not always useful</h2>
<ul>
<li>All these pairs have a correlation of 0.82:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/ascombe-quartet-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="correlation-not-always-useful-2" class="level2">
<h2 class="anchored" data-anchor-id="correlation-not-always-useful-2">Correlation not always useful</h2>
<ul>
<li><p>Correlation is only meaningful in a particular context.</p></li>
<li><p>To help us understand when correlation is meaningful as a summary statistic, we return to the example of predicting a son’s height using his father’s height.</p></li>
</ul>
</section>
<section id="conditional-expectations" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations">Conditional expectations</h2>
<ul>
<li><p>Suppose we are asked to guess the height of a randomly selected son and we don’t know his father’s height.</p></li>
<li><p>Because the distribution of sons’ heights is approximately normal, we know the average height, 69.2, is the value with the highest proportion and would be the prediction with the highest chance of minimizing the error.</p></li>
<li><p>But what if we are told that the father is taller than average, say 72 inches tall, do we still guess 69.2 for the son?</p></li>
</ul>
</section>
<section id="conditional-expectations-1" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-1">Conditional expectations</h2>
<ul>
<li><p>It turns out that, if we were able to collect data from a very large number of fathers that are 72 inches, the distribution of their sons’ heights would be normally distributed.</p></li>
<li><p>This implies that the average of the distribution computed on this subset would be our best prediction.</p></li>
<li><p>We call this approach <em>conditioning</em>.</p></li>
<li><p>The general idea is that we stratify a population into groups and compute summaries in each group.</p></li>
</ul>
</section>
<section id="conditional-expectations-2" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="conditional-expectations-2">Conditional expectations</h2>
<ul>
<li><p>To provide a mathematical description of conditioning, consider that we have a population of pairs of values <span class="math inline">\((x_1,y_1),\dots,(x_n,y_n)\)</span>, for example all father and son heights in England.</p></li>
<li><p>In the previous chapter, we learned that if you take a random pair <span class="math inline">\((X,Y)\)</span>, the expected value and best predictor of <span class="math inline">\(Y\)</span> is <span class="math inline">\(\mbox{E}(Y) = \bar{y}\)</span>, the population average <span class="math inline">\(1/n\sum_{i=1}^n y_i\)</span>.</p></li>
<li><p>However, we are no longer interested in the general population.</p></li>
<li><p>We want to see if we can get better estimates if we know something additional, say from another variable that is correlated with <span class="math inline">\(Y\)</span>.</p></li>
</ul>
</section>
<section id="conditional-expectations-3" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-3">Conditional expectations</h2>
<ul>
<li><p>Instead, we are interested in only the subset of a population with a specific <span class="math inline">\(x_i\)</span> value, 72 inches in our example.</p></li>
<li><p>This subset of the population is also a population, and thus, the same principles and properties we have learned apply.</p></li>
<li><p>The <span class="math inline">\(y_i\)</span> in the subpopulation have a distribution, referred to as the <em>conditional distribution</em>, and this distribution has an expected value referred to as the <em>conditional expectation</em>.</p></li>
</ul>
</section>
<section id="conditional-expectations-4" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="conditional-expectations-4">Conditional expectations</h2>
<ul>
<li><p>In our example, the conditional expectation is the average height of all sons in England with fathers that are 72 inches.</p></li>
<li><p>The statistical notation for the conditional expectation is: <span class="math display">\[
\mbox{E}(Y \mid X = x)
\]</span></p></li>
<li><p>with <span class="math inline">\(x\)</span> representing the fixed value that defines that subset, for example 72 inches.</p></li>
<li><p>this represents the average value of the variable named <span class="math inline">\(Y\)</span> when the variable named <span class="math inline">\(X\)</span> has value <span class="math inline">\(x\)</span></p></li>
</ul>
</section>
<section id="conditional-expectations-5" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-5">Conditional expectations</h2>
<ul>
<li>Similarly, we denote the standard deviation of the strata with:</li>
</ul>
<p><span class="math display">\[
\mbox{SD}(Y \mid X = x) = \sqrt{\mbox{Var}(Y \mid X = x)}
\]</span></p>
</section>
<section id="conditional-expectations-6" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-6">Conditional expectations</h2>
<ul>
<li><p>Because the conditional expectation <span class="math inline">\(E(Y\mid X=x)\)</span> is the best predictor for the random variable <span class="math inline">\(Y\)</span> for an individual in the strata defined by <span class="math inline">\(X=x\)</span>, many data science challenges reduce to estimating this quantity.</p></li>
<li><p>The conditional standard deviation quantifies the precision of the prediction.</p></li>
<li><p>In the example we have been considering, we are interested in computing the average son height <em>conditioned</em> on the father being 72 inches tall.</p></li>
<li><p>We want to estimate <span class="math inline">\(E(Y|X=72)\)</span> using the sample collected by Galton.</p></li>
</ul>
</section>
<section id="conditional-expectations-7" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-7">Conditional expectations</h2>
<ul>
<li><p>We previously learned that the sample average is the preferred approach to estimating the population average.</p></li>
<li><p>A challenge when using this approach is that we don’t have many data points matching exactly one value in our sample.</p></li>
<li><p>For example, we have only:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(galton_heights<span class="sc">$</span>father <span class="sc">==</span> <span class="dv">72</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<ul>
<li>fathers that are exactly 72 inches.</li>
</ul>
</section>
<section id="conditional-expectations-8" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-8">Conditional expectations</h2>
<ul>
<li>If we change the number to 72.5, we get even fewer data points:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(galton_heights<span class="sc">$</span>father <span class="sc">==</span> <span class="fl">72.5</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="conditional-expectations-9" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-9">Conditional expectations</h2>
<ul>
<li><p>A practical way to improve these estimates of the conditional expectations is to define strata of observations with similar value of <span class="math inline">\(x\)</span>.</p></li>
<li><p>In our example, we can round father heights to the nearest inch and assume that they are all 72 inches.</p></li>
<li><p>If we do this, we end up with the following prediction for the son of a father that is 72 inches tall:</p></li>
</ul>
</section>
<section id="conditional-expectations-10" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-10">Conditional expectations</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>conditional_avg <span class="ot">&lt;-</span> galton_heights <span class="sc">|&gt;</span>  </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">round</span>(father) <span class="sc">==</span> <span class="dv">72</span>) <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">mean</span>(son)) <span class="sc">|&gt;</span>  </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(avg) </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>conditional_avg </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70.5</code></pre>
</div>
</div>
<ul>
<li>Note that a 72 inch father is taller than average, specifically (72.0 - 69.1)/2.5 = 1.1 standard deviations taller than the average father.</li>
</ul>
</section>
<section id="conditional-expectations-11" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-11">Conditional expectations</h2>
<ul>
<li><p>Our prediction 70.5 is also taller than average, but only 0.49 standard deviations larger than the average son.</p></li>
<li><p>The sons of 72 inch fathers have <em>regressed</em> some to the average height.</p></li>
<li><p>We notice that the reduction in how many SDs taller is about 0.5, which happens to be the correlation. This is not a coincidence.</p></li>
<li><p>If we want to make a prediction of any height, not just 72 inches, we could apply the same approach to each strata.</p></li>
</ul>
</section>
<section id="conditional-expectations-12" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-12">Conditional expectations</h2>
<ul>
<li>Stratification followed by boxplots lets us see the distribution of each group:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/boxplot-1-run-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conditional-expectations-13" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-13">Conditional expectations</h2>
<ul>
<li><p>Not surprisingly, the centers of the groups are increasing with height.</p></li>
<li><p>Furthermore, these centers appear to follow a linear relationship.</p></li>
<li><p>Below, we plot the averages of each group.</p></li>
<li><p>If we take into account that these averages are random variables with standard errors, the data is consistent with these points following a straight line:</p></li>
</ul>
</section>
<section id="conditional-expectations-14" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-14">Conditional expectations</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/conditional-averages-follow-line-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conditional-expectations-15" class="level2">
<h2 class="anchored" data-anchor-id="conditional-expectations-15">Conditional expectations</h2>
<ul>
<li><p>The fact that these conditional averages follow a line is not a coincidence.</p></li>
<li><p>The line these averages follow is what we call the <em>regression line</em>.</p></li>
<li><p>However, it is not always appropriate to estimate conditional expectations with the regression line, so we also describe Galton’s theoretical justification for using the regression line.</p></li>
</ul>
</section>
<section id="the-regression-line" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line">The regression line</h2>
<ul>
<li>If we are predicting a random variable <span class="math inline">\(Y\)</span> knowing the value of another <span class="math inline">\(X=x\)</span> using a regression line:</li>
<li>then we predict that for every standard deviation, <span class="math inline">\(\sigma_X\)</span>, that <span class="math inline">\(x\)</span> increases above the average <span class="math inline">\(\mu_X\)</span>,</li>
<li>our prediction <span class="math inline">\(\widehat{Y}\)</span> increase <span class="math inline">\(\rho\)</span> standard deviations <span class="math inline">\(\sigma_Y\)</span> above the average <span class="math inline">\(\mu_Y\)</span> with <span class="math inline">\(\rho\)</span> the correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
</ul>
</section>
<section id="the-regression-line-1" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-1">The regression line</h2>
<ul>
<li>The formula for the regression is therefore:</li>
</ul>
<p><span class="math display">\[
\left( \frac{\widehat{Y}-\mu_Y}{\sigma_Y} \right) = \rho \left( \frac{x-\mu_X}{\sigma_X} \right)
\]</span></p>
</section>
<section id="the-regression-line-2" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-2">The regression line</h2>
<ul>
<li>We can rewrite it like this:</li>
</ul>
<p><span class="math display">\[
\widehat{Y} = \mu_Y + \rho \left( \frac{x-\mu_X}{\sigma_X} \right) \sigma_Y
\]</span></p>
<ul>
<li><p>If there is perfect correlation, the regression line predicts an increase that is the same number of SDs.</p></li>
<li><p>If there is 0 correlation, then <span class="math inline">\(X\)</span> does not help predict <span class="math inline">\(Y\)</span> at all we simply predict the average <span class="math inline">\(\bar{Y}\)</span>.</p></li>
<li><p>For values of <span class="math inline">\(|\rho|\)</span> between 0 and 1, the prediction is somewhere in between.</p></li>
<li><p>If the correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is negative, we predict a reduction instead of an increase.</p></li>
</ul>
</section>
<section id="the-regression-line-3" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-3">The regression line</h2>
<ul>
<li><p>Note that if the correlation is positive and lower than 1, our prediction is closer, in standard units, to the average height than the value used to predict, <span class="math inline">\(x\)</span>, is to the average of the <span class="math inline">\(x\)</span>s.</p></li>
<li><p>This is why we call it <em>regression</em>: the son regresses to the average height.</p></li>
<li><p>In fact, the title of Galton’s paper was: <em>Regression toward mediocrity in hereditary stature</em>.</p></li>
</ul>
</section>
<section id="the-regression-line-4" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-4">The regression line</h2>
<ul>
<li>To add regression lines to plots, we will need the above formula in the form:</li>
</ul>
<p><span class="math display">\[
\widehat{Y} = b + mx \mbox{ with slope } m = \rho \frac{\sigma_y}{\sigma_x} \mbox{ and intercept } b=\mu_y - m \mu_x
\]</span></p>
</section>
<section id="the-regression-line-5" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-5">The regression line</h2>
<ul>
<li>Here we add the regression line to the original data:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mu_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(galton_heights<span class="sc">$</span>father) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mu_y <span class="ot">&lt;-</span> <span class="fu">mean</span>(galton_heights<span class="sc">$</span>son) </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>s_x <span class="ot">&lt;-</span> <span class="fu">sd</span>(galton_heights<span class="sc">$</span>father) </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>s_y <span class="ot">&lt;-</span> <span class="fu">sd</span>(galton_heights<span class="sc">$</span>son) </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(galton_heights<span class="sc">$</span>father, galton_heights<span class="sc">$</span>son) </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="sc">|&gt;</span>  </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(father, son)) <span class="sc">+</span>  </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> r <span class="sc">*</span> s_y<span class="sc">/</span>s_x, <span class="at">intercept =</span> mu_y <span class="sc">-</span> r <span class="sc">*</span> s_y<span class="sc">/</span>s_x <span class="sc">*</span> mu_x)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-regression-line-6" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-6">The regression line</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/regression-line-run-1.png" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-regression-line-7" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-7">The regression line</h2>
<ul>
<li>The regression formula implies that if we first standardize the variables, that is subtract the average and divide by the standard deviation, then the regression line has intercept 0 and slope equal to the correlation <span class="math inline">\(\rho\)</span>.</li>
</ul>
</section>
<section id="the-regression-line-8" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-line-8">The regression line</h2>
<ul>
<li>You can make same plot, but using standard units like this:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="sc">|&gt;</span>  </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">scale</span>(father), <span class="fu">scale</span>(son))) <span class="sc">+</span>  </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> r)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regression-improves-precision" class="level2">
<h2 class="anchored" data-anchor-id="regression-improves-precision">Regression improves precision</h2>
<ul>
<li><p>Let’s compare the two approaches to prediction that we have presented:</p>
<ol type="1">
<li><p>Round fathers’ heights to closest inch, stratify, and then take the average.</p></li>
<li><p>Compute the regression line and use it to predict.</p></li>
</ol></li>
<li><p>We use a Monte Carlo simulation sampling <span class="math inline">\(N=50\)</span> families:</p></li>
</ul>
</section>
<section id="regression-improves-precision-1" class="level2">
<h2 class="anchored" data-anchor-id="regression-improves-precision-1">Regression improves precision</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">50</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1983</span>) </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>conditional_avg <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, { </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(galton_heights, N) </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  dat <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">round</span>(father) <span class="sc">==</span> <span class="dv">72</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">avg =</span> <span class="fu">mean</span>(son)) <span class="sc">|&gt;</span>  </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>(avg) </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  }) </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>regression_prediction <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, { </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(galton_heights, N) </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  mu_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>father) </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  mu_y <span class="ot">&lt;-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>son) </span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  s_x <span class="ot">&lt;-</span> <span class="fu">sd</span>(dat<span class="sc">$</span>father) </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  s_y <span class="ot">&lt;-</span> <span class="fu">sd</span>(dat<span class="sc">$</span>son) </span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> <span class="fu">cor</span>(dat<span class="sc">$</span>father, dat<span class="sc">$</span>son) </span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  mu_y <span class="sc">+</span> r<span class="sc">*</span>(<span class="dv">72</span> <span class="sc">-</span> mu_x)<span class="sc">/</span>s_x<span class="sc">*</span>s_y </span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>}) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regression-improves-precision-2" class="level2">
<h2 class="anchored" data-anchor-id="regression-improves-precision-2">Regression improves precision</h2>
<ul>
<li>Although the expected value of these two random variables is about the same:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(conditional_avg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70.49368</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(regression_prediction) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70.50941</code></pre>
</div>
</div>
<ul>
<li>The standard error for the regression prediction is substantially smaller:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(conditional_avg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9635814</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(regression_prediction) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4520833</code></pre>
</div>
</div>
</section>
<section id="regression-improves-precision-3" class="level2">
<h2 class="anchored" data-anchor-id="regression-improves-precision-3">Regression improves precision</h2>
<ul>
<li><p>The prediction obtained with the regression line is therefore much more stable than the prediction obtained using the conditional mean.</p></li>
<li><p>There is an intuitive reason for this.</p></li>
</ul>
</section>
<section id="regression-improves-precision-4" class="level2">
<h2 class="anchored" data-anchor-id="regression-improves-precision-4">Regression improves precision</h2>
<ul>
<li><p>The conditional average is computed on a relatively small subset: the fathers that are about 72 inches tall.</p></li>
<li><p>In fact, in some of the permutations we have no data, which is why we used <code>na.rm=TRUE</code> in our simulation.</p></li>
<li><p>The regression line is estimated using all the data.</p></li>
<li><p>So why not always use the regression line for prediction? Because it is not always appropriate.</p></li>
</ul>
</section>
<section id="regression-improves-precision-5" class="level2">
<h2 class="anchored" data-anchor-id="regression-improves-precision-5">Regression improves precision</h2>
<ul>
<li><p>For example, Anscombe provided cases for which the data does not have a linear relationship.</p></li>
<li><p>So are we justified in using the regression line to predict? Galton answered this in the positive for height data.</p></li>
<li><p>The justification, which we include in the next section, is somewhat more advanced than the rest of the chapter.</p></li>
<li><p>Correlation and the regression slope are a widely used summary statistic, but they are often misused or misinterpreted.</p></li>
</ul>
</section>
<section id="bivariate-normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution">Bivariate normal distribution</h2>
<ul>
<li><p>Anscombe’s examples provide over-simplified cases in which the correlation is not a useful summary.</p></li>
<li><p>But there are many real-life examples.</p></li>
<li><p>The main way we motivate appropriate use of correlation as a summary, involves the <em>bivariate normal distribution</em>.</p></li>
<li><p>When a pair of random variables is approximated by the bivariate normal distribution, scatterplots look like ovals.</p></li>
</ul>
</section>
<section id="bivariate-normal-distribution-1" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-1">Bivariate normal distribution</h2>
<ul>
<li><p>As we saw in earlier they can be thin (high correlation) or circle-shaped (no correlation).</p></li>
<li><p>A more technical way to define the bivariate normal distribution is the following: if <span class="math inline">\(X\)</span> is a normally distributed random variable, <span class="math inline">\(Y\)</span> is also a normally distributed random variable, and the conditional distribution of <span class="math inline">\(Y\)</span> for any <span class="math inline">\(X=x\)</span> is approximately normal, then the pair is approximately bivariate normal.</p></li>
</ul>
</section>
<section id="bivariate-normal-distribution-2" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-2">Bivariate normal distribution</h2>
<ul>
<li>When three or more variables have the property that each pair is bivariate normal, we say the variables follow a <em>multivariate</em> normal distribution or that they are <em>jointly</em> normal.</li>
</ul>
</section>
<section id="bivariate-normal-distribution-3" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-3">Bivariate normal distribution</h2>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/b/b2/Galton%27s_correlation_diagram_1875.jpg" class="img-fluid"></p>
</section>
<section id="bivariate-normal-distribution-4" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-4">Bivariate normal distribution</h2>
<ul>
<li>If we think the height data is well approximated by the bivariate normal distribution, then we should see the normal approximation hold for each strata:</li>
</ul>
</section>
<section id="bivariate-normal-distribution-5" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-5">Bivariate normal distribution</h2>
<div class="cell" data-output-location="slide">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_father =</span> <span class="fu">round</span>((father <span class="sc">-</span> <span class="fu">mean</span>(father)) <span class="sc">/</span> <span class="fu">sd</span>(father))) <span class="sc">|&gt;</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(z_father <span class="sc">%in%</span> <span class="sc">-</span><span class="dv">2</span><span class="sc">:</span><span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span>   </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(<span class="fu">aes</span>(<span class="at">sample =</span> son)) <span class="sc">+</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>( <span class="sc">~</span> z_father)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/qqnorm-of-strata-run-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bivariate-normal-distribution-6" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-6">Bivariate normal distribution</h2>
<ul>
<li><p>Now we come back to defining correlation.</p></li>
<li><p>Galton used mathematical statistics to demonstrate that, when two variables follow a bivariate normal distribution, computing the regression line is equivalent to computing conditional expectations.</p></li>
</ul>
</section>
<section id="bivariate-normal-distribution-7" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-7">Bivariate normal distribution</h2>
<ul>
<li>We don’t show the derivation here, but we can show that under this assumption, for any given value of <span class="math inline">\(x\)</span>, the expected value of the <span class="math inline">\(Y\)</span> in pairs for which <span class="math inline">\(X=x\)</span> is:</li>
</ul>
<p><span class="math display">\[
\mbox{E}(Y | X=x) = \mu_Y +  \rho \frac{x-\mu_X}{\sigma_X}\sigma_Y
\]</span></p>
<p>This is the regression line, with slope <span class="math display">\[\rho \frac{\sigma_Y}{\sigma_X}\]</span> and intercept <span class="math inline">\(\mu_y - m\mu_X\)</span>.</p>
</section>
<section id="bivariate-normal-distribution-8" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-8">Bivariate normal distribution</h2>
<p>This is equivalent to the regression equation we showed earlier which can be written like this:</p>
<p><span class="math display">\[
\frac{\mbox{E}(Y \mid X=x)  - \mu_Y}{\sigma_Y} = \rho \frac{x-\mu_X}{\sigma_X}
\]</span></p>
<ul>
<li><p>This implies that, if our data is approximately bivariate, the regression line gives the conditional probability.</p></li>
<li><p>Therefore, we can obtain a much more stable estimate of the conditional expectation by finding the regression line and using it to predict.</p></li>
</ul>
</section>
<section id="bivariate-normal-distribution-9" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-normal-distribution-9">Bivariate normal distribution</h2>
<ul>
<li>In summary, if our data is approximately bivariate, then the conditional expectation, the best prediction of <span class="math inline">\(Y\)</span> given we know the value of <span class="math inline">\(X\)</span>, is given by the regression line.</li>
</ul>
</section>
<section id="variance-explained" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained">Variance explained</h2>
<ul>
<li>The bivariate normal theory also tells us that the standard deviation of the <em>conditional</em> distribution described above is:</li>
</ul>
<p><span class="math display">\[
\mbox{SD}(Y \mid X=x ) = \sigma_Y \sqrt{1-\rho^2}  
\]</span></p>
<ul>
<li><p>To see why this is intuitive, notice that without conditioning, <span class="math inline">\(\mbox{SD}(Y) = \sigma_Y\)</span>, we are looking at the variability of all the sons.</p></li>
<li><p>But once we condition, we are only looking at the variability of the sons with a tall, 72 inch father.</p></li>
</ul>
</section>
<section id="variance-explained-1" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained-1">Variance explained</h2>
<ul>
<li><p>This group will all tend to be somewhat tall so the standard deviation is reduced.</p></li>
<li><p>Specifically, it is reduced to <span class="math inline">\(\sqrt{1-\rho^2} = \sqrt{1 - 0.25}\)</span> = 0.87 of what it was originally.</p></li>
</ul>
</section>
<section id="variance-explained-2" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained-2">Variance explained</h2>
<ul>
<li><p>We could say that father heights “explain” 13% of the variability observed in son heights.</p></li>
<li><p>The statement “<span class="math inline">\(X\)</span> explains such and such percent of the variability” is commonly used in academic papers.</p></li>
<li><p>In this case, this percent actually refers to the variance (the SD squared).</p></li>
</ul>
</section>
<section id="variance-explained-3" class="level2">
<h2 class="anchored" data-anchor-id="variance-explained-3">Variance explained</h2>
<ul>
<li><p>So if the data is bivariate normal, the variance is reduced by <span class="math inline">\(1-\rho^2\)</span>, so we say that <span class="math inline">\(X\)</span> explains <span class="math inline">\(1- (1-\rho^2)=\rho^2\)</span> (the correlation squared) of the variance.</p></li>
<li><p>But it is important to remember that the “variance explained” statement only makes sense when the data is approximated by a bivariate normal distribution.</p></li>
</ul>
</section>
<section id="there-are-two-regression-lines" class="level2">
<h2 class="anchored" data-anchor-id="there-are-two-regression-lines">There are two regression lines</h2>
<ul>
<li><p>We computed a regression line to predict the son’s height from father’s height.</p></li>
<li><p>We used these calculations:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>mu_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(galton_heights<span class="sc">$</span>father) </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>mu_y <span class="ot">&lt;-</span> <span class="fu">mean</span>(galton_heights<span class="sc">$</span>son) </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>s_x <span class="ot">&lt;-</span> <span class="fu">sd</span>(galton_heights<span class="sc">$</span>father) </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>s_y <span class="ot">&lt;-</span> <span class="fu">sd</span>(galton_heights<span class="sc">$</span>son) </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(galton_heights<span class="sc">$</span>father, galton_heights<span class="sc">$</span>son) </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>m_1 <span class="ot">&lt;-</span>  r <span class="sc">*</span> s_y <span class="sc">/</span> s_x </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> mu_y <span class="sc">-</span> m_1<span class="sc">*</span>mu_x </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>which gives us the function <span class="math inline">\(\mbox{E}(Y\mid X=x) =\)</span> 37.3 + 0.46 <span class="math inline">\(x\)</span>.</li>
</ul>
</section>
<section id="there-are-two-regression-lines-1" class="level2">
<h2 class="anchored" data-anchor-id="there-are-two-regression-lines-1">There are two regression lines</h2>
<ul>
<li><p>What if we want to predict the father’s height based on the son’s? It is important to know that this is not determined by computing the inverse function: <span class="math inline">\(x = \{ \mbox{E}(Y\mid X=x) -\)</span> 37.3 <span class="math inline">\(\} /\)</span> 0.5.</p></li>
<li><p>We need to compute <span class="math inline">\(\mbox{E}(X \mid Y=y)\)</span>.</p></li>
<li><p>Since the data is approximately bivariate normal, the theory described earlier tells us that this conditional expectation will follow a line with slope and intercept:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m_2 <span class="ot">&lt;-</span>  r <span class="sc">*</span> s_x <span class="sc">/</span> s_y </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>b_2 <span class="ot">&lt;-</span> mu_x <span class="sc">-</span> m_2 <span class="sc">*</span> mu_y </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="there-are-two-regression-lines-2" class="level2">
<h2 class="anchored" data-anchor-id="there-are-two-regression-lines-2">There are two regression lines</h2>
<ul>
<li><p>So we get <span class="math inline">\(\mbox{E}(X \mid Y=y) =\)</span> 40.9 + 0.41y.</p></li>
<li><p>Again, we see regression to the average: the prediction for the father is closer to the father average than the son heights <span class="math inline">\(y\)</span> is to the son average.</p></li>
<li><p>Next we show plot showing the two regression lines, with blue for the predicting son heights with father heights, and red for predicting father heights with son heights:</p></li>
</ul>
</section>
<section id="there-are-two-regression-lines-3" class="level2">
<h2 class="anchored" data-anchor-id="there-are-two-regression-lines-3">There are two regression lines</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="29-regression_files/figure-html/two-regression-lines-run-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="linear-models" class="level2">
<h2 class="anchored" data-anchor-id="linear-models">Linear models</h2>
<ul>
<li><p>We are now ready to understand the connection between regression and <em>linear models</em>.</p></li>
<li><p>We have described how, if data is bivariate normal, then the conditional expectations follow the regression line.</p></li>
<li><p>The fact that the conditional expectation is a line is not an extra assumption, but rather a derived result.</p></li>
</ul>
</section>
<section id="linear-models-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-1">Linear models</h2>
<ul>
<li><p>However, in practice it is common to explicitly write down a model that describes the relationship between two or more variables using a <em>linear model</em>.</p></li>
<li><p>We note that <em>linear</em> here does not refer to lines exclusively, but rather to the fact that the conditional expectation is a linear combination of known quantities.</p></li>
</ul>
</section>
<section id="linear-models-2" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-2">Linear models</h2>
<ul>
<li><p>In mathematics, when we multiply each variable by a constant and then add them together, we say we formed a <em>linear combination</em> of the variables.</p></li>
<li><p>For example, <span class="math inline">\(3x - 4y + 5z\)</span> is a linear combination of <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>, and <span class="math inline">\(z\)</span>.</p></li>
</ul>
</section>
<section id="linear-models-3" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-3">Linear models</h2>
<ul>
<li><p>We can also add a constant so <span class="math inline">\(2 + 3x - 4y + 5z\)</span> is also a linear combination of <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>, and <span class="math inline">\(z\)</span>.</p></li>
<li><p>We previously described how if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are bivariate normal, then if we look at only the pairs with <span class="math inline">\(X=x\)</span>, then <span class="math inline">\(Y \mid X=x\)</span> follows a normal distribution with expected value <span class="math inline">\(\mu_Y +  \rho \frac{x-\mu_X}{\sigma_X}\sigma_Y\)</span>, which is a linear function of <span class="math inline">\(x\)</span>, and standard deviation <span class="math inline">\(\sigma_Y \sqrt{1-\rho^2}\)</span> that does not depend on <span class="math inline">\(x\)</span>.</p></li>
</ul>
</section>
<section id="linear-models-4" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-4">Linear models</h2>
<ul>
<li>Note that if we write:</li>
</ul>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 x + \varepsilon
\]</span></p>
<ul>
<li>If we assume <span class="math inline">\(\varepsilon\)</span> follows a normal distribution with expected value 0 and fixed standard deviation, then <span class="math inline">\(Y\)</span> has the same properties as the regression setup gave us: it follows a normal distribution, the expected value is a linear function <span class="math inline">\(x\)</span>, and the standard deviation does not depend on <span class="math inline">\(x\)</span>.</li>
</ul>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>In statistical textbooks, the <span class="math inline">\(\varepsilon\)</span>s are referred to as “errors,” which originally represented measurement errors in the initial applications of these models.</p></li>
<li><p>These errors were associated with inaccuracies in measuring height, weight, or distance.</p></li>
<li><p>However, the term “error” is now used more broadly, even when the <span class="math inline">\(\varepsilon\)</span>s do not necessarily signify an actual error.</p></li>
<li><p>For instance, in the case of height, if someone is 2 inches taller than expected, based on their parents’ height, those 2 inches should not be considered an error.</p></li>
<li><p>Despite its lack of descriptive accuracy, the term “error” is employed to elucidate the unexplained variability in the model, unrelated to other included terms.</p></li>
</ul>
</div>
</div>
</section>
<section id="linear-models-5" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-5">Linear models</h2>
<ul>
<li>If we were to specify a linear model for Galton’s data, we would denote the <span class="math inline">\(N\)</span> observed father heights with <span class="math inline">\(x_1, \dots, x_n\)</span>, then we model the <span class="math inline">\(N\)</span> son heights we are trying to predict with:</li>
</ul>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i, \, i=1,\dots,N.  
\]</span></p>
<ul>
<li>Here <span class="math inline">\(x_i\)</span> is the father’s height, which is fixed (not random) due to the conditioning, and <span class="math inline">\(Y_i\)</span> is the random son’s height that we want to predict.</li>
</ul>
</section>
<section id="linear-models-6" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-6">Linear models</h2>
<ul>
<li><p>We can further assume that <span class="math inline">\(\varepsilon_i\)</span> are independent from each other and all have the same standard deviation.</p></li>
<li><p>In the above model, we know the <span class="math inline">\(x_i\)</span>, but to have a useful model for prediction, we need <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p></li>
<li><p>We estimate these from the data.</p></li>
</ul>
</section>
<section id="linear-models-7" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-7">Linear models</h2>
<ul>
<li><p>Once we do this, we can predict son’s heights for any father’s height <span class="math inline">\(x\)</span>.</p></li>
<li><p>Although this model is exactly the same one we derived earlier by assuming bivariate normal data, a somewhat nuanced difference is that, in the first approach, we assumed the data was bivariate normal and the linear model was derived, not assumed.</p></li>
</ul>
</section>
<section id="linear-models-8" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-8">Linear models</h2>
<ul>
<li><p>In practice, linear models are just assumed without necessarily assuming normality: the distribution of the <span class="math inline">\(\varepsilon\)</span>s is not necessarily specified.</p></li>
<li><p>Nevertheless, if your data is bivariate normal, the above linear model holds.</p></li>
<li><p>If your data is not bivariate normal, then you will need to have other ways of justifying the model.</p></li>
</ul>
</section>
<section id="linear-models-9" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-9">Linear models</h2>
<ul>
<li><p>One reason linear models are popular is that they are <em>interpretable</em>.</p></li>
<li><p>In the case of Galton’s data, we can interpret the data like this: due to inherited genes, the son’s height prediction grows by <span class="math inline">\(\beta_1\)</span> for each inch we increase the father’s height <span class="math inline">\(x\)</span>.</p></li>
<li><p>Because not all sons with fathers of height <span class="math inline">\(x\)</span> are of equal height, we need the term <span class="math inline">\(\varepsilon\)</span>, which explains the remaining variability.</p></li>
</ul>
</section>
<section id="linear-models-10" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-10">Linear models</h2>
<ul>
<li><p>This remaining variability includes the mother’s genetic effect, environmental factors, and other biological randomness.</p></li>
<li><p>Given how we wrote the model above, the intercept <span class="math inline">\(\beta_0\)</span> is not very interpretable, as it is the predicted height of a son with a father with no height.</p></li>
<li><p>Due to regression to the mean, the prediction will usually be a bit larger than 0.</p></li>
</ul>
</section>
<section id="linear-models-11" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-11">Linear models</h2>
<ul>
<li>To make the slope parameter more interpretable, we can rewrite the model slightly as:</li>
</ul>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 (x_i - \bar{x}) + \varepsilon_i, \, i=1,\dots,N  
\]</span></p>
<ul>
<li><p>with <span class="math inline">\(\bar{x} = 1/N \sum_{i=1}^N x_i\)</span> the average of the <span class="math inline">\(x\)</span>.</p></li>
<li><p>In this case, <span class="math inline">\(\beta_0\)</span> represents the height when <span class="math inline">\(x_i = \bar{x}\)</span>, which is the height of the son of an average father.</p></li>
</ul>
</section>
<section id="linear-models-12" class="level2">
<h2 class="anchored" data-anchor-id="linear-models-12">Linear models</h2>
<ul>
<li>Later, we will see how the linear model representation permits us to use the same mathematical frameworks in other contexts and to achieve more complicated goals than predict one variable from another.</li>
</ul>
</section>
<section id="least-squares-estimates" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates">Least Squares Estimates</h2>
<ul>
<li><p>For linear models to be useful, we have to estimate the unknown <span class="math inline">\(\beta\)</span>s.</p></li>
<li><p>The standard approach is to find the values that minimize the distance of the fitted model to the data.</p></li>
<li><p>Specifically, we find the <span class="math inline">\(\beta\)</span>s that minize the least squares (LS) equation show below.</p></li>
</ul>
</section>
<section id="least-squares-estimates-1" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-1">Least Squares Estimates</h2>
<ul>
<li>For Galton’s data, the LS equation looks like this:</li>
</ul>
<p><span class="math display">\[
RSS = \sum_{i=1}^n \left\{  y_i - \left(\beta_0 + \beta_1 x_i \right)\right\}^2  
\]</span></p>
</section>
<section id="least-squares-estimates-2" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-2">Least Squares Estimates</h2>
<ul>
<li><p>The quantity we try to minimize is called the residual sum of squares (RSS).</p></li>
<li><p>Once we find the values that minimize the RSS, we will call the values the least squares estimates (LSE) and denote them by placing a <em>hat</em> over the parameters.</p></li>
</ul>
</section>
<section id="least-squares-estimates-3" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-3">Least Squares Estimates</h2>
<ul>
<li><p>In our example we use <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>.</p></li>
<li><p>We will demonstrate how we find these values using the previously defined <code>galton_heights</code> dataset.</p></li>
</ul>
</section>
<section id="least-squares-estimates-4" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-4">Least Squares Estimates</h2>
<ul>
<li>Let’s start by writing a function that computes the RSS for any pair of values <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>rss <span class="ot">&lt;-</span> <span class="cf">function</span>(beta0, beta1, data){ </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  resid <span class="ot">&lt;-</span> galton_heights<span class="sc">$</span>son <span class="sc">-</span> (beta0 <span class="sc">+</span> beta1<span class="sc">*</span>galton_heights<span class="sc">$</span>father) </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(resid<span class="sc">^</span><span class="dv">2</span>)) </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>} </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>So for any pair of values, we get an RSS.</li>
</ul>
</section>
<section id="least-squares-estimates-5" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-5">Least Squares Estimates</h2>
<ul>
<li>Here is a plot of the RSS as a function of <span class="math inline">\(\beta_1\)</span>, when we keep the <span class="math inline">\(\beta_0\)</span> fixed at 25.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/rss-versus-estimate-run-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="least-squares-estimates-6" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-6">Least Squares Estimates</h2>
<ul>
<li><p>We can see a clear minimum for <span class="math inline">\(\beta_1\)</span> at around 0.65.</p></li>
<li><p>However, this minimum for <span class="math inline">\(\beta_1\)</span> is for when <span class="math inline">\(\beta_0 = 25\)</span>, a value we arbitrarily picked.</p></li>
<li><p>We don’t know if (25, 0.65) is the pair that minimizes the equation across all possible pairs.</p></li>
<li><p>Trial and error is not going to work in this case.</p></li>
</ul>
</section>
<section id="least-squares-estimates-7" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-7">Least Squares Estimates</h2>
<ul>
<li><p>We could search for a minimum within a fine grid of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> values, but this is unnecessarily time-consuming since we can use calculus.</p></li>
<li><p>Specifically, we take the partial derivatives, set them to 0, and solve for <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>.</p></li>
<li><p>Of course, if we have many parameters, these equations can get rather complex.</p></li>
</ul>
</section>
<section id="least-squares-estimates-8" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-estimates-8">Least Squares Estimates</h2>
<ul>
<li><p>There are functions in R that do these calculations for us.</p></li>
<li><p>To learn the mathematics behind this, you can consult a book on linear models.</p></li>
</ul>
</section>
<section id="the-lm-function" class="level2">
<h2 class="anchored" data-anchor-id="the-lm-function">The <code>lm</code> function</h2>
<ul>
<li><p>In R, we can obtain the least squares estimates using the <code>lm</code> function.</p></li>
<li><p>To fit the model:</p></li>
</ul>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i
\]</span></p>
<ul>
<li>with <span class="math inline">\(Y_i\)</span> being the son’s height and <span class="math inline">\(x_i\)</span> being the father’s height, we can use this code to obtain the least squares estimates.</li>
</ul>
</section>
<section id="the-lm-function-1" class="level2">
<h2 class="anchored" data-anchor-id="the-lm-function-1">The <code>lm</code> function</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(son <span class="sc">~</span> father, <span class="at">data =</span> galton_heights) </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fit<span class="sc">$</span>coefficients </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      father 
  37.287605    0.461392 </code></pre>
</div>
</div>
<ul>
<li><p>The most common way we use <code>lm</code> is by using the character <code>~</code> to let <code>lm</code> know which is the variable we are predicting (left of <code>~</code>) and which we are using to predict (right of <code>~</code>).</p></li>
<li><p>The intercept is added automatically to the model that will be fit.</p></li>
</ul>
</section>
<section id="the-lm-function-2" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-lm-function-2">The <code>lm</code> function</h2>
<ul>
<li><p>The object <code>fit</code> includes more information.</p></li>
<li><p>We can use the function <code>summary</code> to extract more of this information:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = son ~ father, data = galton_heights)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.3543 -1.5657 -0.0078  1.7263  9.4150 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.28761    4.98618   7.478 3.37e-12 ***
father       0.46139    0.07211   6.398 1.36e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.45 on 177 degrees of freedom
Multiple R-squared:  0.1878,    Adjusted R-squared:  0.1833 
F-statistic: 40.94 on 1 and 177 DF,  p-value: 1.36e-09</code></pre>
</div>
</div>
</section>
<section id="the-lm-function-3" class="level2">
<h2 class="anchored" data-anchor-id="the-lm-function-3">The <code>lm</code> function</h2>
<ul>
<li><p>To understand some of the information included in this summary, we need to remember that the LSE are random variables.</p></li>
<li><p>Mathematical statistics gives us some ideas of the distribution of these random variables.</p></li>
</ul>
</section>
<section id="lse-are-random-variables" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables">LSE are random variables</h2>
<ul>
<li><p>The LSE is derived from the data <span class="math inline">\(y_1,\dots,y_N\)</span>, which are a realization of random variables <span class="math inline">\(Y_1, \dots, Y_N\)</span>.</p></li>
<li><p>This implies that our estimates are random variables.</p></li>
</ul>
</section>
<section id="lse-are-random-variables-1" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables-1">LSE are random variables</h2>
<ul>
<li>To see this, we can run a Monte Carlo simulation in which we assume the son and father height data defines a population, take a random sample of size <span class="math inline">\(N=50\)</span>, and compute the regression slope coefficient for each one:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">50</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>lse <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, { </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(galton_heights, N, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lm</span>(son <span class="sc">~</span> father, <span class="at">data =</span> _) <span class="sc">|&gt;</span>  </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coef</span>() </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>}) </span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>lse <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">beta_0 =</span> lse[<span class="dv">1</span>,], <span class="at">beta_1 =</span> lse[<span class="dv">2</span>,])  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="lse-are-random-variables-2" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables-2">LSE are random variables</h2>
<ul>
<li>We can see the variability of the estimates by plotting their distributions:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/lse-distributions-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lse-are-random-variables-3" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables-3">LSE are random variables</h2>
<ul>
<li><p>The reason these look normal is because the central limit theorem applies here as well: for large enough <span class="math inline">\(N\)</span>, the least squares estimates will be approximately normal with expected value <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, respectively.</p></li>
<li><p>The standard errors are a bit complicated to compute, but mathematical theory does allow us to compute them and they are included in the summary provided by the <code>lm</code> function.</p></li>
</ul>
</section>
<section id="lse-are-random-variables-4" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables-4">LSE are random variables</h2>
<ul>
<li>The function <code>summary</code> shows us the standard error estimates:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample_n</span>(galton_heights, N, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span>  </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(son <span class="sc">~</span> father, <span class="at">data =</span> _) <span class="sc">|&gt;</span>  </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span>  </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error  t value     Pr(&gt;|t|)
(Intercept) 24.5722201 11.0734543 2.219020 0.0312467290
father       0.6479396  0.1602234 4.043975 0.0001896386</code></pre>
</div>
</div>
</section>
<section id="lse-are-random-variables-5" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables-5">LSE are random variables</h2>
<ul>
<li>You can see that the standard errors estimates reported above are close to the standard errors from the simulation:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>lse <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="at">se_0 =</span> <span class="fu">sd</span>(beta_0), <span class="at">se_1 =</span> <span class="fu">sd</span>(beta_1)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      se_0      se_1
1 8.669471 0.1256726</code></pre>
</div>
</div>
<ul>
<li><p>The <code>summary</code> function also reports t-statistics (<code>t value</code>) and p-values (<code>Pr(&gt;|t|)</code>).</p></li>
<li><p>The t-statistic is not actually based on the central limit theorem, but rather on the assumption that the <span class="math inline">\(\varepsilon\)</span>s follow a normal distribution.</p></li>
</ul>
</section>
<section id="lse-are-random-variables-6" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="lse-are-random-variables-6">LSE are random variables</h2>
<ul>
<li><p>Under this assumption, mathematical theory tells us that the LSE divided by their standard error, <span class="math display">\[
\hat{\beta}_0 / \widehat{\mbox{SE}}(\hat{\beta}_0 ) \quad \mbox{and} \quad
\hat{\beta}_1 / \widehat{\mbox{SE}}(\hat{\beta}_1 )
\]</span> follow a t-distribution with <span class="math inline">\(N-p\)</span> degrees of freedom, with <span class="math inline">\(p\)</span> the number of parameters in our model.</p></li>
<li><p>In our example <span class="math inline">\(p=2\)</span>, and the two p-values are obtained from testing the null hypothesis that <span class="math inline">\(\beta_0 = 0\)</span> and <span class="math inline">\(\beta_1=0\)</span>, respectively.</p></li>
<li><p>Remember that, as we described earlier, for large enough <span class="math inline">\(N\)</span>, the CLT works and the t-distribution becomes almost the same as the normal distribution.</p></li>
</ul>
</section>
<section id="lse-are-random-variables-7" class="level2">
<h2 class="anchored" data-anchor-id="lse-are-random-variables-7">LSE are random variables</h2>
<ul>
<li><p>Also, notice that we can construct confidence intervals, but we will soon learn about <strong>broom</strong>, an add-on package that makes this easy.</p></li>
<li><p>Although we do not show examples in this book, hypothesis testing with regression models is commonly used in epidemiology and economics to make statements such as “the effect of A on B was statistically significant after adjusting for X, Y, and Z”.</p></li>
<li><p>However, several assumptions have to hold for these statements to be true.</p></li>
</ul>
</section>
<section id="predicted-values-are-random-variables" class="level2">
<h2 class="anchored" data-anchor-id="predicted-values-are-random-variables">Predicted values are random variables</h2>
<ul>
<li><p>Once we fit our model, we can obtain prediction of <span class="math inline">\(Y\)</span> by plugging in the estimates into the regression model.</p></li>
<li><p>For example, if the father’s height is <span class="math inline">\(x\)</span>, then our prediction <span class="math inline">\(\hat{Y}\)</span> for the son’s height will be:</p></li>
</ul>
<p><span class="math display">\[\widehat{Y} = \widehat{\beta}_0 + \widehat{\beta}_1 x\]</span></p>
</section>
<section id="predicted-values-are-random-variables-1" class="level2">
<h2 class="anchored" data-anchor-id="predicted-values-are-random-variables-1">Predicted values are random variables</h2>
<ul>
<li><p>When we plot <span class="math inline">\(\widehat{Y}\)</span> versus <span class="math inline">\(x\)</span>, we see the regression line.</p></li>
<li><p>Keep in mind that the prediction <span class="math inline">\(\widehat{Y}\)</span> is also a random variable and mathematical theory tells us what the standard errors are.</p></li>
</ul>
</section>
<section id="predicted-values-are-random-variables-2" class="level2">
<h2 class="anchored" data-anchor-id="predicted-values-are-random-variables-2">Predicted values are random variables</h2>
<ul>
<li><p>If we assume the errors are normal, or have a large enough sample size, we can use theory to construct confidence intervals as well.</p></li>
<li><p>In fact, the <strong>ggplot2</strong> layer <code>geom_smooth(method = "lm")</code> that we previously used plots <span class="math inline">\(\widehat{Y}\)</span> and surrounds it by confidence intervals:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>galton_heights <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(son, father)) <span class="sc">+</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="predicted-values-are-random-variables-3" class="level2">
<h2 class="anchored" data-anchor-id="predicted-values-are-random-variables-3">Predicted values are random variables</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/father-son-regression-run-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="predicted-values-are-random-variables-4" class="level2">
<h2 class="anchored" data-anchor-id="predicted-values-are-random-variables-4">Predicted values are random variables</h2>
<ul>
<li><p>The R function <code>predict</code> takes an <code>lm</code> object as input and returns the prediction.</p></li>
<li><p>If requested, the standard errors and other information from which we can construct confidence intervals is provided:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> galton_heights <span class="sc">|&gt;</span> <span class="fu">lm</span>(son <span class="sc">~</span> father, <span class="at">data =</span> _)  </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">se.fit =</span> <span class="cn">TRUE</span>) </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(y_hat) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "fit"            "se.fit"         "df"             "residual.scale"</code></pre>
</div>
</div>
</section>
<section id="diagnostic-plots" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots">Diagnostic plots</h2>
<ul>
<li><p>When the linear model is assumed, rather than derived, all interpretations depend on the usefulness of the model.</p></li>
<li><p>The <code>lm</code> function will fit the model and return summaries even when the model is wrong and not useful.</p></li>
<li><p>Visually inspecting residuals, defined as the difference between observed values and predicted values:</p></li>
</ul>
<p><span class="math display">\[
r = Y - \widehat{Y} = Y - \left(\widehat{\beta}_0 - \widehat{\beta}_1 x_i\right),
\]</span></p>
</section>
<section id="diagnostic-plots-1" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-1">Diagnostic plots</h2>
<ul>
<li><p>and summaries of the residuals, is a powerful way to diagnose if the model is useful.</p></li>
<li><p>Note that the residuals can be thought of estimates of the errors since:</p></li>
</ul>
<p><span class="math display">\[
\varepsilon = Y - \left(\beta_0 + \beta_1 x_i \right).
\]</span></p>
<ul>
<li><p>In fact residuals are often denoted as <span class="math inline">\(\widehat{\varepsilon}\)</span>.</p></li>
<li><p>This motivates several <em>diagnostic</em> plots.</p></li>
</ul>
</section>
<section id="diagnostic-plots-2" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-2">Diagnostic plots</h2>
<ul>
<li><p>Because we observe <span class="math inline">\(r\)</span>, but don’t observe <span class="math inline">\(\varepsilon\)</span>, we based the plots on the residuals.</p>
<ol type="1">
<li><p>Because the errors are assumed not to depend on the expected value of <span class="math inline">\(Y\)</span>, a plot of <span class="math inline">\(r\)</span> versus the fitted values <span class="math inline">\(\widehat{Y}\)</span> should show no relationship.</p></li>
<li><p>In cases in which we assume the errors follow a normal distribution, a qqplot of standardized <span class="math inline">\(r\)</span> should fall on a line when plotted against theoretical quantiles.</p></li>
</ol></li>
</ul>
</section>
<section id="diagnostic-plots-3" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-3">Diagnostic plots</h2>
<ol start="3" type="1">
<li>Because we assume the standard deviation of the errors is constant, if we plot the absolute value of the residuals, it should appear constant.</li>
</ol>
</section>
<section id="diagnostic-plots-4" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-4">Diagnostic plots</h2>
<ul>
<li><p>We prefer plots rather than summaries based on correlation because correlation is not always the best summary of association.</p></li>
<li><p>The function <code>plot</code> applied to an <code>lm</code> object automatically plots these.</p></li>
</ul>
</section>
<section id="diagnostic-plots-5" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-5">Diagnostic plots</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/diagnostic-plots-run-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="diagnostic-plots-6" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-6">Diagnostic plots</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="diagnostic-plots-7" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="diagnostic-plots-7">Diagnostic plots</h2>
<ul>
<li><p>This function can produce six different plots, and the argument <code>which</code> let’s you specify which you want to see.</p></li>
<li><p>You can learn more by reading the <code>plot.lm</code> help file.</p></li>
<li><p>However, some of the plots are based on more advanced concepts beyond the scope of this book.</p></li>
<li><p>To learn more, we recommend an advanced book on regression analysis.</p></li>
<li><p>We later introduce data analysis challenges in which we may decide to not to include certain variables in the model.</p></li>
</ul>
</section>
<section id="diagnostic-plots-8" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots-8">Diagnostic plots</h2>
<ul>
<li>In these cases, an important diagnostic test to add checks if the residuals are related to variables not included in the model.</li>
</ul>
</section>
<section id="the-regression-fallacy" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy">The regression fallacy</h2>
<ul>
<li><p>Wikipedia defines the <em>sophomore slump</em> as:</p></li>
<li><blockquote class="blockquote">
<p>A sophomore slump or sophomore jinx or sophomore jitters refers to an instance in which a second, or sophomore, effort fails to live up to the standards of the first effort.</p>
</blockquote></li>
<li><p>It is commonly used to refer to the apathy of students (second year of high school, college or university), the performance of athletes (second season of play), singers/bands (second album), television shows (second seasons) and movies (sequels/prequels).</p></li>
</ul>
</section>
<section id="the-regression-fallacy-1" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-1">The regression fallacy</h2>
<ul>
<li><p>In Major League Baseball, the rookie of the year (ROY) award is given to the first-year player who is judged to have performed the best.</p></li>
<li><p>The <em>sophomore slump</em> phrase is used to describe the observation that ROY award winners don’t do as well during their second year.</p></li>
<li><p>For example, this Fox Sports article[^linear-models-1] asks “Will MLB’s tremendous rookie class of 2015 suffer a sophomore slump?”.</p></li>
</ul>
</section>
<section id="the-regression-fallacy-2" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-2">The regression fallacy</h2>
<ul>
<li><p><a href="https://www.baseball-reference.com/bullpen/Sophomore_slump">Sophomore Slump</a></p></li>
<li><p>You can find the data in this R package: <a href="https://cran.r-project.org/web/packages/Lahman/index.html">Lahman</a></p></li>
<li><p>Does the data confirm the existence of a sophomore slump? Let’s take a look.</p></li>
<li><p>Examining the data for a widely used measure of success, the batting average, we see that this observation holds true for the top performing ROYs:</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Lahman' was built under R version 4.4.3</code></pre>
</div>
</div>
</section>
<section id="the-regression-fallacy-3" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-3">The regression fallacy</h2>
<ul>
<li><p>In fact, the proportion of players that have a lower batting average during their sophomore year is 0.7090909.</p></li>
<li><p>So is it “jitters” or “jinx”? To answer this question, let’s turn our attention to all the players that played the 2013 and 2014 seasons and batted more than 130 times (minimum to win Rookie of the Year).</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'playerID'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
</section>
<section id="the-regression-fallacy-4" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-4">The regression fallacy</h2>
<ul>
<li>The same pattern arises when we look at the top performers: batting averages go down for most of the top performers.</li>
</ul>
<ul>
<li>But these are not rookies! Also, look at what happens to the worst performers of 2013:</li>
</ul>
<ul>
<li><p>Their batting averages mostly go up! Is this some sort of reverse sophomore slump? It is not.</p></li>
<li><p>There is no such thing as a sophomore slump.</p></li>
</ul>
</section>
<section id="the-regression-fallacy-5" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-5">The regression fallacy</h2>
<ul>
<li>This is all explained with a simple statistical fact: the correlation for performance in two separate years is high, but not perfect.</li>
</ul>
</section>
<section id="the-regression-fallacy-6" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-6">The regression fallacy</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="29-regression_files/figure-html/regression-fallacy-1.png" class="img-fluid figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-regression-fallacy-7" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="the-regression-fallacy-7">The regression fallacy</h2>
<ul>
<li>The correlation is 0.46 and the data look very much like a bivariate normal distribution, which means we predict a 2014 batting average <span class="math inline">\(Y\)</span> for any given player that had a 2013 batting average <span class="math inline">\(X\)</span> with:</li>
</ul>
<p><span class="math display">\[ \frac{Y - .255}{.032} = 0.46 \left( \frac{X - .261}{.023}\right) \]</span></p>
<ul>
<li><p>Because the correlation is not perfect, regression tells us that, on average, expect high performers from 2013 to do a bit worse in 2014.</p></li>
<li><p>It’s not a jinx; it’s just due to chance.</p></li>
</ul>
</section>
<section id="the-regression-fallacy-8" class="level2">
<h2 class="anchored" data-anchor-id="the-regression-fallacy-8">The regression fallacy</h2>
<ul>
<li>The ROY are selected from the top values of <span class="math inline">\(X\)</span>, so it is expected that <span class="math inline">\(Y\)</span> will regress to the mean.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/datasciencelabs\.github\.io\/2025\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/datasciencelabs/2025/blob/main/slides/linear-models/29-regression.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer></body></html>