---
title: "Project Outlines"
format: html
editor: visual
---

## Projects

For the projects in this term we will make use of the NHANES data set.  Please use the NHANES package and you can either use NHANES, or NHANESraw, but you must explain your choice and why you picked that one.  Most of you will likely want to use NHANES as it is a probability sample from the US, whereas NHANESraw is a survey weighted population.  But those of you taking Epidemiology courses may want to look at using survey weights in your analysis, and for that you need to use NHANESraw.

  
  We would greatly prefer if each team has a fairly distinct project, either by age group, outcome or methodology.
  
## Housekeeping

You **must** use GitHub for the project and each member of the team **must** make their own commits.  You will be graeded on your contributions. 

Within one week you should pick the topic (see below) and outline your analysis and work plans.  Try to specify which team members will be responsibe for each of the activities.  Try to give weekly breakdowns on what you will get done, as a way to ensure that you do not try to do too much, or too little.  This should be in a document in your GitHub repo called "Outline.txt" and should be in plain text. Once this is ready please let your TF know and they will go over it with Robert and Anthony and give feedback on whether it seems sufficient.  You will edit this document as you proceed with the project, providing updates and details on your team's progress.

Your final report should be a Quarto document, complete with images and references as needed. It should be possible to clone the repo, as an R-project and render the document.

In addition to the report that you will jointly produce each of you will need to submit, in your GitHub repo, a file with your name and it should indicate how much effort (hours/week) you put into the project. What things you worked on etc.

## Topics and Ideas

In addition to modeling the data to ask about interesting demographic and health outcomes. You can instead choose to examine some set of statistical models or approaches.  Examples include: 
  * use of multiple imputation methods to address issues of missing values
  * use of spline models in regression to allow for interpretable non-linear associations with continuous variables and inference in those models
  * use of sample survey methods to be able to derive population estimates.
  * use of classical machine learning methods such as logistic regression, randomForests and other tools to try to get a sense of the structure of the data.
  * develop a Posit Connect (nee Shiny) application to support user interactions with some part of the NHANES data. The solution should include design documents, use cases and some discussion of what tools you enabled and why.

### Age groups

We suggest looking at age groups [2-18], [19-40] and [40+].  You can look at just one of these and then fit models and explain your choices etc.

You will likely want to consider important covariates such as age, sex, race and interactions between these.  Once you pick an outcome variable to explore you should ask your favorite LLM for advice on risk factors and potential interactions.

Outcomes that are interesting differ by age groups.  Older people, [40+] are less healthy and show more unusual patterns that are associated with disease and aging.

[2-18] - these individuals are growing and their relationships between height, weight, BMI etc are not the same as we would use for adults. Usually children are referred to growth charts.

[19-35] are largely healthy and active.

### Missing Values

There are a lot of missing values in some of the variables.  These are not likely to be useful in your modeling, as you would likely need to spend a fair amount of time trying to understand why observations are missing.

Studying this, can be one of the topics.  There are a large number of methods that can help to understand how missing data might affect any estimates you want to make.  And in real situations, you almost always have missing data.

### Possible Responses

There are a large number of different responses you can think about modeling. Systolic blood pressure, especially in older populations is very interesting.

You can think about disease risk - ie Diabetes, Depression, Sleep, Smoking, BMI.
You will probably find it easiest to model continuous, or relatively continuous responses, but if your group wants to look at categorical variables as repsonses, that is fine.  We will try to help give you advice on models etc.


